DROP TABLE IF EXISTS books;

CREATE TABLE IF NOT EXISTS books(
    id SERIAL,
    title VARCHAR(250) NOT NULL,
    description VARCHAR(250) NOT NULL,
    price NUMERIC NOT NULL,
    PRIMARY KEY (id)
);
